image: mcr.microsoft.com/dotnet/sdk:5.0

before_script:
    - cd ./Sources
    - dotnet restore

build:
    stage: build
    tags:
        - docker
    script:
        - dotnet build -c Release --no-restore
        - dotnet publish -c Release --no-restore -o $CI_PROJECT_DIR/build/release
    artifacts:
        paths:
            - $CI_PROJECT_DIR/build/release

test:
    stage: test
    tags:
        - docker
    script:
        - dotnet test --no-restore
